apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v2tnw4ltr-java-springboot 
  janus-idp.io/tekton: v2tnw4ltr-java-springboot
  backstage.io/kubernetes-id: v2tnw4ltr-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v2tnw4ltr-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml